### ISSUE TITLE
When I try to run Dcase.py,an error occurs.

### ISSUE THREAD

**Issue by sansuialways** [APILASTRI/DCASE_Task2_UMINHO#11]

**Comment by sansuialways** [comment]
Traceback (most recent call last): 

  File "Dcase.py", line 587, in <module>     
 b = numpy_dataset_stream_noaugment(files_Read)  
 File "Dcase.py", line 298, in numpy_dataset_stream_noaugment    
 newlist = newlist.reshape(newlist.shape[0] * newlist.shape[1], newlist.shape[2]) 
 IndexError: tuple index out of range.

Why?
